<?php /** @noinspection PhpFullyQualifiedNameUsageInspection */
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Cap\Rma\Block\Customer\Dashboard $block */
?>

<?php if ($block->isLoggedIn()): ?>
    <?php // Form & Orders ?>
    <div class="block block-dashboard-rma-form-orders">
        <div class="block-title">
            <strong><?php /* @escapeNotVerified */ echo __('Orders & Request Form'); ?></strong>
        </div>
        <div class="block-content">
            <?php $orders = $block->getCustomerOrdersCanRequest(); ?>
            <?php if (count($orders)): ?>
                <?php echo $block->getChildHtml('dashboard.form'); ?>
                <?php echo $block->getChildHtml('dashboard.orders'); ?>
            <?php else: ?>
                <div class="message info">
                    <div>
                        <?php /* @escapeNotVerified */ echo __('You have no order that meets the request conditions.'); ?>
                        <?php if($block->getPolicyLink()): ?>
                            <span> <a href="<?php echo $block->escapeUrl($block->getPolicyLink()); ?>" title="<?php $block->escapeHtml(__('Return Policy')) ?>"><?php /* @escapeNotVerified */ echo __('Return Policy'); ?></a></span>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endif ?>
        </div>
    </div>
    <?php // Requests ?>
    <div class="block block-dashboard-rma-requests">
        <div class="block-title">
            <strong><?php /* @escapeNotVerified */ echo __('My Requests'); ?></strong>
        </div>
        <div class="block-content">
            <?php $requests = $block->getCustomerRequests(); ?>
            <?php if (count($requests)): ?>
                <?php echo $block->getChildHtml('dashboard.requests'); ?>
            <?php else: ?>
                <div class="message notice">
                    <div><?php /* @escapeNotVerified */ echo __('No Request'); ?></div>
                </div>
            <?php endif ?>
        </div>
    </div>
<?php else: ?>
    <div class="message error">
        <div><?php /* @escapeNotVerified */ echo __('You must be logged in'); ?></div>
    </div>
<?php endif; ?>
