<?php

/** @var \Cap\Rma\Block\Customer\Request $block */

?>

<?php if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom">
        <?php echo $block->getPagerHtml(); ?>
    </div>
<?php endif; ?>
<?php $requests = $block->getRewardHistory(); ?>
<?php if($requests && count($requests)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items orders-history" id="requests-table">
            <caption class="caption"><?php echo __('Records'); ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?php echo __('ID'); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($requests as $request): ?>
                    <tr>
                        <td><?php echo $request->getRequestId(); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom">
            <?php echo $block->getPagerHtml(); ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
