<?php /** @noinspection PhpFullyQualifiedNameUsageInspection */
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Cap\Rma\Block\Customer\Dashboard $block */
?>

<div class="box box-rma-form">
    <div class="box-content">
        <form id="rma-form" class="form" action="<?php echo $block->getFormAction() ?>" method="post">
            <fieldset class="fieldset">
                <div class="field name">
                    <label class="label" for="customerName"><?php /* @escapeNotVerified */ echo __('Name'); ?>&nbsp;</label>
                    <a href="<?php echo $block->escapeUrl($block->getCustomerEditLink()); ?>"><?php echo $block->escapeHtml($block->getCustomerName()) ?></a>
                    <input type="hidden" class="hidden" name="customerName" value="<?php echo $block->escapeHtml($block->getCustomerName()) ?>"/>
                </div>

                <div class="field email">
                    <label class="label" for="customerEmail"><?php /* @escapeNotVerified */ echo __('Email'); ?>&nbsp;</label>
                    <a href="<?php echo $block->escapeUrl($block->getCustomerEditLink()); ?>"><?php echo $block->escapeHtml($block->getCustomerEmail()) ?></a>
                    <input type="hidden" name="customerEmail" value="<?php echo $block->escapeHtml($block->getCustomerEmail()) ?>"/>
                </div>

                <div class="field order required">
                    <label class="label" for="orderIncrementId"><?php /* @escapeNotVerified */ echo __('Order'); ?></label>
                    <div class="control">
                        <select id="orderIncrementId" name="orderIncrementId">
                            <option value="" selected disabled hidden></option>
                            <?php $orders = $block->getCustomerOrdersCanRequest(); ?>
                            <?php /** @var \Magento\Sales\Model\Order $order */ ?>
                            <?php foreach ($orders as $order): ?>
                                    <option value="<?php echo $block->escapeHtml($order->getIncrementId()); ?>"><?php /* @escapeNotVerified */ echo $order->getIncrementId(); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>

                <?php if ($block->getTypesEnable()): ?>
                    <?php $types = $block->getTypesOptions(); ?>
                    <div class="field request-type required">
                        <label class="label" for="requestType"><?php /* @escapeNotVerified */
                            echo __('Request Type'); ?></label>
                        <div class="control">
                            <select id="requestType" name="requestType">
                                <option value="" selected disabled hidden></option>
                                <?php foreach ($types as $type): ?>
                                    <option value="<?php echo $block->escapeHtml(__($type['value'])); ?>"><?php echo $block->escapeHtml(__($type['label'])); ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                <?php endif ?>

                <div class="field description required">
                    <label class="label" for="description"><?php /* @escapeNotVerified */ echo __('Details'); ?></label>
                    <div class="control">
                        <textarea name="description" rows="5"></textarea>
                    </div>
                </div>
            </fieldset>

            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action send primary" title="<?php echo __('Send'); ?>">
                        <span><?php echo /* @escapeNotVerified */ __('Submit'); ?></span>
                    </button>
                </div>
                <div class="secondary">
                    <button type="reset" class="action reset secondary" title="<?php echo __('Reset'); ?>">
                        <span><?php echo /* @escapeNotVerified */ __('Reset'); ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>