<?php /** @noinspection PhpFullyQualifiedNameUsageInspection */
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Cap\Rma\Block\Customer\Dashboard $block */
?>

<div class="box box-rma-form">
    <div class="box-content">
        <form id="rma-form" class="form" action="<?php echo $block->getFormAction() ?>" method="post">
            <fieldset class="fieldset">
                <div class="field name required">
                    <label class="label" for="customerName"><?php /* @escapeNotVerified */ echo __('Name'); ?></label>
                    <div class="control">
                        <input type="hidden" name="customerName" value="<?php echo $block->escapeHtml($block->getCustomerName()) ?>"/>
                        <input type="text" disabled="disabled" name="customerName" class="input-text" value="<?php echo $block->escapeHtml($block->getCustomerName()) ?>"/>
                    </div>
                </div>
                <div class="field email required">
                    <label class="label" for="customerEmail"><?php /* @escapeNotVerified */ echo __('Email'); ?></label>
                    <div class="control">
                        <input type="hidden" name="customerEmail" value="<?php echo $block->escapeHtml($block->getCustomerEmail()) ?>"/>
                        <input type="text" disabled="disabled" name="customerEmail" class="input-text" value="<?php echo $block->escapeHtml($block->getCustomerEmail()) ?>"/>
                    </div>
                </div>

<!--                <div class="field order required">-->
<!--                    <label class="label" for="orderId">--><?php ///* @escapeNotVerified */ echo __('Order'); ?><!--</label>-->
<!--                    <div class="control">-->
<!--                        <select id="orderId" name="orderId">-->
<!--                            <option value="" selected disabled hidden></option>-->
<!--                            --><?php //foreach ($orders as $order): ?>
<!--                                <option value="--><?php //echo $order->getId(); ?><!--">--><?php //echo $order->getIncrementId(); ?><!--</option>-->
<!--                            --><?php //endforeach; ?>
<!--                        </select>-->
<!--                    </div>-->
<!--                </div>-->

                <?php $typesValues = $block->getConfigTypesValue(); ?>
                <?php if (count($typesValues)): ?>
                    <div class="field request-type required">
                        <label class="label" for="requestType"><?php /* @escapeNotVerified */ echo __('Request Type'); ?></label>
                        <div class="control">
                            <select id="requestType" name="requestType">
                                <option value="" selected disabled hidden></option>
                                <?php foreach ($typesValues as $type): ?>
                                    <option value="<?php echo $block->escapeHtml(__($type)); ?>"><?php echo $block->escapeHtml(__($type)); ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                <?php endif; ?>

                <div class="field description required">
                    <label class="label" for="description"><?php /* @escapeNotVerified */ echo __('Details'); ?></label>
                    <div class="control">
                        <textarea name="description"></textarea>
                    </div>
                </div>
            </fieldset>

            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action send primary" title="<?php echo __('Send'); ?>">
                        <span><?php echo /* @escapeNotVerified */ __('Submit'); ?></span>
                    </button>
                </div>
                <div class="secondary">
                    <button type="reset" class="action reset secondary" title="<?php echo __('Reset'); ?>">
                        <span><?php echo /* @escapeNotVerified */ __('Reset'); ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>